# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: farm_services.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'farm_services.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x66\x61rm_services.proto\x12\x08\x66\x61rmtech\"\x1e\n\x0b\x43ropRequest\x12\x0f\n\x07\x63rop_id\x18\x01 \x01(\t\"*\n\x10MoistureResponse\x12\x16\n\x0emoisture_level\x18\x01 \x01(\x02\"\x1f\n\x0f\x46orecastRequest\x12\x0c\n\x04\x64\x61te\x18\x01 \x01(\t\"M\n\x10\x46orecastResponse\x12\x13\n\x0btemperature\x18\x01 \x01(\x02\x12\x10\n\x08humidity\x18\x02 \x01(\x02\x12\x12\n\nconditions\x18\x03 \x01(\t2V\n\x0b\x43ropMonitor\x12G\n\x10GetMoistureLevel\x12\x15.farmtech.CropRequest\x1a\x1a.farmtech.MoistureResponse\"\x00\x32_\n\x0eWeatherStation\x12M\n\x12GetWeatherForecast\x12\x19.farmtech.ForecastRequest\x1a\x1a.farmtech.ForecastResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'farm_services_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_CROPREQUEST']._serialized_start=33
  _globals['_CROPREQUEST']._serialized_end=63
  _globals['_MOISTURERESPONSE']._serialized_start=65
  _globals['_MOISTURERESPONSE']._serialized_end=107
  _globals['_FORECASTREQUEST']._serialized_start=109
  _globals['_FORECASTREQUEST']._serialized_end=140
  _globals['_FORECASTRESPONSE']._serialized_start=142
  _globals['_FORECASTRESPONSE']._serialized_end=219
  _globals['_CROPMONITOR']._serialized_start=221
  _globals['_CROPMONITOR']._serialized_end=307
  _globals['_WEATHERSTATION']._serialized_start=309
  _globals['_WEATHERSTATION']._serialized_end=404
# @@protoc_insertion_point(module_scope)
