# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import farm_services_pb2 as farm__services__pb2

GRPC_GENERATED_VERSION = '1.66.2'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in farm_services_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class CropMonitorStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetMoistureLevel = channel.unary_unary(
                '/farmtech.CropMonitor/GetMoistureLevel',
                request_serializer=farm__services__pb2.CropRequest.SerializeToString,
                response_deserializer=farm__services__pb2.MoistureResponse.FromString,
                _registered_method=True)


class CropMonitorServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetMoistureLevel(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CropMonitorServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetMoistureLevel': grpc.unary_unary_rpc_method_handler(
                    servicer.GetMoistureLevel,
                    request_deserializer=farm__services__pb2.CropRequest.FromString,
                    response_serializer=farm__services__pb2.MoistureResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'farmtech.CropMonitor', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('farmtech.CropMonitor', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class CropMonitor(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetMoistureLevel(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmtech.CropMonitor/GetMoistureLevel',
            farm__services__pb2.CropRequest.SerializeToString,
            farm__services__pb2.MoistureResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class WeatherStationStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetWeatherForecast = channel.unary_unary(
                '/farmtech.WeatherStation/GetWeatherForecast',
                request_serializer=farm__services__pb2.ForecastRequest.SerializeToString,
                response_deserializer=farm__services__pb2.ForecastResponse.FromString,
                _registered_method=True)


class WeatherStationServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetWeatherForecast(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WeatherStationServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetWeatherForecast': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWeatherForecast,
                    request_deserializer=farm__services__pb2.ForecastRequest.FromString,
                    response_serializer=farm__services__pb2.ForecastResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'farmtech.WeatherStation', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('farmtech.WeatherStation', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class WeatherStation(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetWeatherForecast(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/farmtech.WeatherStation/GetWeatherForecast',
            farm__services__pb2.ForecastRequest.SerializeToString,
            farm__services__pb2.ForecastResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
